### ISSUE TITLE
?will this code be opensourced  in the futrue?

### ISSUE THREAD

**Issue by mrlonely001** [alapini/wmdx#1]
will this code be opensourced  in the futrue?

**Comment by alapini** [comment]
Yes @mrlonely001, I'm planning to publish it by the end of November

**Comment by mrlonely001** [comment]
> Yes @mrlonely001, I'm planning to publish it by the end of November

Come On，I am looking forward to it

**Comment by mrlonely001** [comment]
Is there a version that you can push ?
